#ifndef PARALLELCONSTANTS
#define PARALLELCONSTANTS

#define WARP_SIZE 32

#define THREADS_CONVERT 256
#define ELEMS_CONVERT 2

#define THREADS_MERGESORT 512
#define ELEMS_MERGESORT 2


#define SUB_BLOCK_SIZE 256
#define THREADS_GEN_RANKS 128

#define THREADS_PADDING 128
#define ELEMS_PADDING 32

#define MAX_VAL DBL_MAX 

#define THREADS_CHECKERROES 512
#define ELEMS_CHECKERROES 2

#define THREAD_NUM 256
#define THREAD_ELEM 64

#define TIMEWINDOW 5000


#endif // !PARALLELCONSTANTS
#pragma once
